modLoader="javafml"
loaderVersion="[39,)"
license="ARR"
[[mods]]
modId="species"
version="1.20.1-2.3-forge"
displayName="Species"
logoFile= "species.png"
authors="Ninni, Noon, Bornulhu, FloofHips, GLaDOS edition"
description='''
A mod that adds fictional mobs to the game, with cool and unique functions

Contributors:
- lunarbunten
- Orcinus

'''
[[dependencies.species]]
    modId="forge"
    mandatory=true
    versionRange="[39,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.species]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20,1.21)"
    ordering="NONE"
    side="BOTH"
